# Generated by Django 5.2.17 on 2026-09-15 07:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('client_name', models.CharField(blank=True, default='', max_length=200)),
                ('area_type', models.CharField(choices=[('national_park', 'National park'), ('safari_area', 'Safari area'), ('conservancy', 'Conservancy'), ('concession', 'Concession'), ('community', 'Community area'), ('other', 'Other')], default='other', max_length=32)),
                ('boundary', models.JSONField(blank=True, help_text='GeoJSON MultiPolygon, WGS84', null=True)),
                ('boundary_source', models.CharField(blank=True, choices=[('shapefile', 'Shapefile'), ('geojson', 'GeoJSON'), ('kml', 'KML'), ('drawn', 'Drawn')], max_length=16, null=True)),
                ('area_km2', models.FloatField(default=0.0)),
                ('timezone', models.CharField(default='Africa/Harare', max_length=64)),
                ('grid_cell_size_m', models.PositiveIntegerField(default=1000)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organisation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApuBase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=32)),
                ('call_sign', models.CharField(blank=True, default='', max_length=64)),
                ('location', models.JSONField(help_text='GeoJSON Point')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organisation')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apu_bases', to='areas.area')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FeatureLayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('kind', models.CharField(choices=[('roads', 'Roads'), ('water', 'Water')], max_length=16)),
                ('geometry', models.JSONField(help_text='GeoJSON geometry / Feature / FeatureCollection, WGS84')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_layers', to='areas.area')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='GrtsCell',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('label', models.CharField(max_length=16)),
                ('grts_order', models.PositiveIntegerField()),
                ('geometry', models.JSONField(help_text='GeoJSON Polygon')),
                ('centroid', models.JSONField(help_text='GeoJSON Point')),
                ('min_lon', models.FloatField()),
                ('min_lat', models.FloatField()),
                ('max_lon', models.FloatField()),
                ('max_lat', models.FloatField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='areas.area')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organisation')),
            ],
            options={
                'ordering': ['grts_order'],
            },
        ),
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('score', models.FloatField()),
                ('level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=16)),
                ('factors', models.JSONField(default=list)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to='areas.area')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to='areas.grtscell')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organisation')),
            ],
            options={
                'ordering': ['-date', '-score'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('apu_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sectors', to='areas.apubase')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='areas.area')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organisation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='grtscell',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cells', to='areas.sector'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('apu_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='areas.apubase')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='areas.area')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organisation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('visit_target', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True, default='')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='areas.area')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organisation')),
                ('cells', models.ManyToManyField(blank=True, related_name='assignments', to='areas.grtscell')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='areas.team')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddConstraint(
            model_name='apubase',
            constraint=models.UniqueConstraint(fields=('area', 'code'), name='uniq_base_code_per_area'),
        ),
        migrations.AddConstraint(
            model_name='featurelayer',
            constraint=models.UniqueConstraint(fields=('area', 'kind'), name='uniq_layer_kind_per_area'),
        ),
        migrations.AddConstraint(
            model_name='riskscore',
            constraint=models.UniqueConstraint(fields=('cell', 'date'), name='uniq_risk_per_cell_date'),
        ),
        migrations.AddConstraint(
            model_name='grtscell',
            constraint=models.UniqueConstraint(fields=('area', 'grts_order'), name='uniq_grts_order_per_area'),
        ),
    ]
