# Generated by Django 5.2.17 on 2026-09-15 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tombstone',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=32)),
                ('object_id', models.UUIDField()),
                ('area_id', models.UUIDField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organisation')),
            ],
            options={
                'indexes': [models.Index(fields=['organisation', 'kind', 'deleted_at'], name='core_tombst_organis_24c4de_idx')],
            },
        ),
    ]
