# Generated by Django 5.2.17 on 2026-09-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('content', models.BinaryField()),
                ('size', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
