# Generated by Django 5.2.17 on 2026-09-15 11:15

import dashboard.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('patrol_summary', 'patrol_summary'), ('incident_report', 'incident_report'), ('wildlife_census', 'wildlife_census'), ('threat_intelligence', 'threat_intelligence'), ('grts_survey', 'grts_survey'), ('ranger_performance', 'ranger_performance'), ('donor_report', 'donor_report'), ('zpwma_compliance', 'zpwma_compliance')], max_length=32)),
                ('format', models.CharField(choices=[('pdf', 'pdf'), ('csv', 'csv'), ('geojson', 'geojson')], max_length=8)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('failed', 'Failed')], default='ready', max_length=8)),
                ('title', models.CharField(max_length=255)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('anonymised', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, max_length=255, upload_to=dashboard.models.report_upload_to)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organisation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(default=dashboard.models.new_share_token, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organisation')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='dashboard.report')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
