# Generated by Django 5.2.17 on 2026-09-15 07:25

import accounts.models
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('platform_admin', 'Platform admin'), ('org_admin', 'Organisation admin'), ('manager', 'Manager'), ('ranger', 'Ranger'), ('researcher', 'Researcher'), ('viewer', 'Viewer (NGO/Government)')], default='ranger', max_length=32)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('language', models.CharField(choices=[('en', 'English'), ('sn', 'Shona'), ('nd', 'Ndebele')], default='en', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('totp_secret', models.CharField(blank=True, default='', max_length=64)),
                ('totp_last_step', models.BigIntegerField(blank=True, help_text='Replay protection', null=True)),
                ('must_change_password', models.BooleanField(default=False)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('key', models.CharField(default=accounts.models._new_token_key, max_length=40, primary_key=True, serialize=False)),
                ('device_id', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('plan', models.CharField(choices=[('pilot', 'Pilot'), ('standard', 'Standard'), ('enterprise', 'Enterprise')], default='pilot', max_length=16)),
                ('max_rangers', models.PositiveIntegerField(default=10)),
                ('max_managers', models.PositiveIntegerField(default=3)),
                ('max_areas', models.PositiveIntegerField(default=1)),
                ('modules', models.JSONField(blank=True, default=list)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('grace_days', models.PositiveIntegerField(default=14)),
                ('status', models.CharField(choices=[('active', 'Active'), ('grace', 'Grace'), ('suspended', 'Suspended')], default='active', max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoginLockout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=320, unique=True)),
                ('failures', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(help_text='Short upper-case code used at ranger sign-in', max_length=32, unique=True)),
                ('country', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('grace', 'Grace'), ('suspended', 'Suspended')], default='active', max_length=16)),
                ('deployment', models.CharField(choices=[('shared', 'Shared cloud'), ('dedicated', 'Dedicated instance')], default='shared', max_length=16)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
