# Generated by Django 5.2.17 on 2026-09-15 07:25

import django.db.models.deletion
import field.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('areas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('common_name', models.CharField(max_length=128)),
                ('scientific_name', models.CharField(max_length=128, unique=True)),
                ('shona_name', models.CharField(blank=True, default='', max_length=128)),
                ('ndebele_name', models.CharField(blank=True, default='', max_length=128)),
                ('iucn_status', models.CharField(choices=[('LC', 'LC'), ('NT', 'NT'), ('VU', 'VU'), ('EN', 'EN'), ('CR', 'CR'), ('EW', 'EW'), ('EX', 'EX'), ('DD', 'DD'), ('NE', 'NE')], default='NE', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'species',
                'ordering': ['common_name'],
            },
        ),
        migrations.CreateModel(
            name='Patrol',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('client_uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('patrol_type', models.CharField(choices=[('foot', 'Foot'), ('vehicle', 'Vehicle'), ('horseback', 'Horseback'), ('boat', 'Boat')], default='foot', max_length=16)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], default='active', max_length=16)),
                ('distance_m', models.FloatField(default=0)),
                ('duration_s', models.PositiveIntegerField(default=0)),
                ('distance_from_client', models.BooleanField(default=False)),
                ('duration_from_client', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('debrief_audio', models.CharField(blank=True, max_length=500, null=True)),
                ('apu_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrols', to='areas.apubase')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patrols', to='areas.area')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organisation')),
                ('ranger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patrols', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrols', to='areas.team')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SafetyAlert',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('client_uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('panic', 'Panic button'), ('dead_mans_switch', "Dead man's switch")], default='panic', max_length=24)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=16)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('accuracy_m', models.FloatField(blank=True, null=True)),
                ('battery_pct', models.IntegerField(blank=True, null=True)),
                ('signal_level', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organisation')),
                ('ranger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='safety_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('client_uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('wildlife', 'Wildlife'), ('threat', 'Threat'), ('carcass', 'Carcass'), ('habitat', 'Habitat'), ('infrastructure', 'Infrastructure'), ('other', 'Other')], db_index=True, max_length=16)),
                ('subtype', models.CharField(blank=True, max_length=64, null=True)),
                ('species_name', models.CharField(blank=True, max_length=128, null=True)),
                ('count', models.PositiveIntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('mixed', 'Mixed'), ('unknown', 'Unknown')], max_length=8, null=True)),
                ('male_count', models.PositiveIntegerField(blank=True, null=True)),
                ('female_count', models.PositiveIntegerField(blank=True, null=True)),
                ('age_class', models.CharField(blank=True, choices=[('adult', 'Adult'), ('juvenile', 'Juvenile'), ('mixed', 'Mixed'), ('unknown', 'Unknown')], max_length=8, null=True)),
                ('behaviour', models.CharField(blank=True, max_length=255, null=True)),
                ('severity', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=8, null=True)),
                ('direction_of_travel', models.CharField(blank=True, max_length=32, null=True)),
                ('alert_manager', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('accuracy_m', models.FloatField(blank=True, null=True)),
                ('ai_species_confidence', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('voice_transcript', models.TextField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='areas.area')),
                ('cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='areas.grtscell')),
                ('observer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organisation')),
                ('patrol', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='observations', to='field.patrol')),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='field.species')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('audio', 'Audio')], max_length=8)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('file', models.FileField(max_length=255, upload_to=field.models.media_upload_to)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organisation')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='field.observation')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('observation', 'sha256'), name='uniq_media_per_observation')],
            },
        ),
        migrations.CreateModel(
            name='PositionPing',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('patrol_client_uuid', models.UUIDField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('accuracy_m', models.FloatField(blank=True, null=True)),
                ('battery_pct', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organisation')),
                ('ranger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_pings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['ranger', '-recorded_at'], name='field_posit_ranger__9bd3c0_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrackPoint',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('recorded_at', models.DateTimeField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('accuracy_m', models.FloatField(blank=True, null=True)),
                ('speed_mps', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='track_points', to='areas.grtscell')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organisation')),
                ('patrol', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='track_points', to='field.patrol')),
            ],
            options={
                'ordering': ['recorded_at'],
                'constraints': [models.UniqueConstraint(fields=('patrol', 'recorded_at'), name='uniq_trackpoint_time')],
            },
        ),
    ]
