# Generated by Django 5.2.17 on 2026-09-15 11:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('field', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_id', models.UUIDField(db_index=True)),
                ('alert_type', models.CharField(choices=[('safety', 'Safety'), ('threat', 'Threat')], max_length=8)),
                ('action', models.CharField(choices=[('acknowledged', 'Acknowledged'), ('dispatched', 'Dispatched'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled'), ('note', 'Note')], max_length=16)),
                ('note', models.TextField(blank=True, default='')),
                ('responder_ids', models.JSONField(blank=True, default=list)),
                ('at', models.DateTimeField(db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organisation')),
            ],
            options={
                'ordering': ['at'],
            },
        ),
    ]
