# Generated by Django 5.2.17 on 2026-09-19 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
        ('field', '0002_alertevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyalert',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_alerts', to='areas.area'),
        ),
        migrations.AddField(
            model_name='safetyalert',
            name='details',
            field=models.JSONField(blank=True, help_text='HWC details log (spec v1.5 §A2)', null=True),
        ),
        migrations.AddField(
            model_name='safetyalert',
            name='details_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='taxon_group',
            field=models.CharField(choices=[('mammal', 'Mammal'), ('bird', 'Bird'), ('reptile', 'Reptile'), ('amphibian', 'Amphibian'), ('fish', 'Fish'), ('invertebrate', 'Invertebrate')], db_index=True, default='mammal', max_length=16),
        ),
        migrations.AlterField(
            model_name='safetyalert',
            name='kind',
            field=models.CharField(choices=[('panic', 'Panic button'), ('dead_mans_switch', "Dead man's switch"), ('human_wildlife_conflict', 'Human-wildlife conflict')], default='panic', max_length=24),
        ),
    ]
