# Generated by Django 5.2.17 on 2026-09-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0004_species_catalogue'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrol',
            name='distance_clean_m',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
