# Generated by Django 5.2.17 on 2026-09-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='channel',
            field=models.CharField(choices=[('sms', 'SMS'), ('push', 'Push'), ('email', 'Email')], max_length=8),
        ),
    ]
